In [ ]:
Assignment Questions

In [ ]:
1.Using Numpy to generate an array of 25 random numbers sampled from a standard normal distribution

In [1]:
import numpy as np
np.random.rand(25)

array([0.42951892, 0.83937862, 0.36154961, 0.25169826, 0.81448817,
       0.22757046, 0.591568  , 0.44961986, 0.72342953, 0.07687409,
       0.23715562, 0.10768246, 0.97964811, 0.84861838, 0.70676166,
       0.76618057, 0.64046084, 0.52186007, 0.88989076, 0.66328702,
       0.32150149, 0.07458928, 0.01972102, 0.19305488, 0.90297615])

In [ ]:
2.Create an array of 20 linear spaced points between 0 and 1

In [3]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
3.Declare a numpy array of values from 1 to 100 and make it into 10*10 matrix

In [4]:
import numpy as np
array = np.arange(100).reshape(10,10)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
4.Using the previously defind matrix print rows 1,5,6

In [5]:
print(array[[1,5,6]])

[[10 11 12 13 14 15 16 17 18 19]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]


In [ ]:
5.Using the previously defined matrix print elements from 3rd row to 10th row

In [6]:
print(array[3:])

[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
6.Using the previously defined matrix print all the elements from 4th row to 8th row

In [7]:
print(array[0:10,3:8])

[[ 3  4  5  6  7]
 [13 14 15 16 17]
 [23 24 25 26 27]
 [33 34 35 36 37]
 [43 44 45 46 47]
 [53 54 55 56 57]
 [63 64 65 66 67]
 [73 74 75 76 77]
 [83 84 85 86 87]
 [93 94 95 96 97]]


In [ ]:
7.Using the same matrix print values from 3rd row 2nd column to 5th row 8th column

In [8]:
print(array[2:5,1:8])

[[21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]
 [41 42 43 44 45 46 47]]


In [ ]:
8.Write a code to generate random 1000 numbers each in range (0,1) such that the count of all random points like are almost same

In [9]:
np.random.rand(100)

array([0.01396053, 0.98897114, 0.73444254, 0.56974755, 0.83341848,
       0.36736093, 0.75895563, 0.55980075, 0.04355711, 0.90469001,
       0.64802117, 0.84117218, 0.84214888, 0.06064596, 0.94532356,
       0.72150446, 0.01964926, 0.29510753, 0.93693316, 0.93899894,
       0.49387278, 0.66089664, 0.10726318, 0.0939635 , 0.01736276,
       0.8217772 , 0.20113399, 0.12534199, 0.41760868, 0.16817302,
       0.66425835, 0.00602307, 0.43661621, 0.37714472, 0.54041498,
       0.17443768, 0.31001777, 0.21328062, 0.2966284 , 0.52584878,
       0.61686896, 0.10455304, 0.00679126, 0.38293024, 0.25779894,
       0.93926423, 0.5937985 , 0.49271421, 0.91519024, 0.80654339,
       0.34533005, 0.64755665, 0.25046138, 0.58348511, 0.64553508,
       0.05313907, 0.46961598, 0.65667984, 0.88360165, 0.88908988,
       0.75652437, 0.87509854, 0.06763371, 0.14894583, 0.26858137,
       0.79475185, 0.06515381, 0.34016754, 0.86224104, 0.9065075 ,
       0.46736951, 0.68158367, 0.51979988, 0.83118649, 0.45610

In [ ]:
9.Write the commands to get standard deviation, mean,median,mode for a given vector

In [10]:
a = np.array([[7, 2], [5, 4]])
np.mean(a)

4.5

In [11]:
np.median(a)

4.5

In [12]:
np.std(a)

1.8027756377319946

In [13]:
a = np.array([[7, 1, 1, 7],
             [9, 4, 3, 8],
             [6, 1, 9, 7],
             [9, 7, 2, 5],
             [5, 1, 5, 9]])
a

array([[7, 1, 1, 7],
       [9, 4, 3, 8],
       [6, 1, 9, 7],
       [9, 7, 2, 5],
       [5, 1, 5, 9]])

In [14]:
from scipy import stats
stats.mode(a)

ModeResult(mode=array([[9, 1, 1, 7]]), count=array([[2, 3, 1, 2]]))